name: Deploy to staging
on:
  push:
    branches:
      - "main"

jobs:
  redeploy_apps:
    runs-on: ubuntu-latest
    name: Deploying all apps to staging cluster

    steps:
      - name: SSH into the server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          chmod 600 ~/ssh_key
          ssh -i ~/ssh_key ubuntu@ec2-18-212-108-238.compute-1.amazonaws.com
          cd bms/ && git pull
          pnpm install
          pnpm run build
          pm2 restart http-server
          pm2 restart fe-server
          pm2 restart ws-server
